import mysql.connector as mys
mycon=mys.connect(host='localhost',user='root',passwd='')
mycursor=mycon.cursor()
#mycursor.execute('create database info')
mycursor.execute('use info')
#mycursor.execute('create table studentinfo(Rollno int,Name varchar(50), Marks float)')
#mycursor.execute('insert into studentinfo values(1,"Abhinav",99)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(2,"Abhineet",70)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(3,"Anush",78)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(4,"Anushula",98)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(5,"Ayush",89)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(6,"B.Lakshya",88)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(7,"Bhavna",80)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(8,"Bhagmati",78)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(9,"Brian",90)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(10,"Bruce",99)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(11,"Eena",99)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(12,"Elena",77)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(13,"Eyenna",87)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(14,"Gurjeet",86)')
mycon.commit()
#mycursor.execute('insert into studentinfo values(15,"Gurmeet",91)')
mycon.commit()
print('Welcome to the student portal teachers of 12 A')
print('Portal can do following things:')
print('1. View student record')
print('2.Delete a record from students record')
print('3.Insert a record in students record')
print('4. View records who scored less than 80')
print('5.Update marks of particular student')
ans='yes'
while ans=='yes'.lower() or 'Yes'.lower() or 'yEs'.lower() or 'yeS'.lower() or 'YEs'.lower() or 'yES'.lower() or 'YeS'.lower() or 'YES'.lower():
    ID=input('Enter the ID:')
    passwd=int(input('Enter the password'))
    if ID=='NCSG' and passwd==123:
        answ=int(input('Which option would you prefer(1,2,3,4,5):'))
        if answ==1:
            mycursor.execute('select*from studentinfo')
            p=mycursor.fetchall()
            for i in p:
                print(i[0],i[1],i[2])
        elif answ==2:
           roll=int(input('Enter the rollno. that has to be deleted:'))
           mycursor.execute('delete from studentinfo where Rollno=%s'%(roll,))
           mycon.commit()
           mycursor.execute('select*from studentinfo')
           z=mycursor.fetchall()
           for i in z:
               print(i[0],i[1],i[2])
        elif answ==3:
           mycursor.execute('select*from studentinfo')
           a=mycursor.fetchall()
           print(a)
           rollno=int(input('Enter the rollno:'))
           name=input('Enter the name')
           marks=float(input('Enter the marks'))
           mycursor.execute('insert into studentinfo values(%s,"%s",%s)'%(rollno,name,marks))
           mycon.commit()
           mycursor.execute('select*from studentinfo')
           w=mycursor.fetchall()
           for i in w:
               print(i[0],i[1],i[2])
        elif answ==4:
            print('Records of the students who scored less than 80:')
            mycursor.execute('select*from studentinfo where Marks<80')
            s=mycursor.fetchall()
            for i in s:
                print(i[0],i[1],i[2])
        elif answ==5:
            mycursor.execute('select*from studentinfo')
            f=mycursor.fetchall()
            for i in f:
                print(i[0],i[1],i[2])
            roll=int(input('Enter the rollno:'))
            marks=int(input('Enter the marks:'))
            mycursor.execute('update studentinfo set Marks=%s where Rollno=%s',(marks,roll))
            mycon.commit()
            mycursor.execute('select*from studentinfo')
            o=mycursor.fetchall()
            for i in o:
                print(i[0],i[1],i[2])
        
    else:
        print('Invalid cerendentials')
    ans=input('Do you want to continue?')
print('Thank You')
print('Exiting')
           
